version: '3.8'

services:
  pre-commit:
    security_opt:
      - no-new-privileges:true
    read_only: true
    image: python:3.11
    environment:
      - HTTP_PROXY=http://host.docker.internal:39353
      - HTTPS_PROXY=http://host.docker.internal:39353
    # Добавили apt-get update && apt-get install -y default-jre для установки Java
    command: >
      bash -c "apt-get update && apt-get install -y default-jre
      && pip install pre-commit
      && git config --global --add safe.directory /workdir
      && pre-commit run --all-files"
    volumes:
      - .:/workdir
      - pre-commit-cache:/root/.cache/pre-commit
    working_dir: /workdir

volumes:
  pre-commit-cache:
